name: ci-wf
on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - synchronize
  push:
    branches:
      - develop
jobs:
  linting-job:
    runs-on: ubuntu
    steps:
      - name: welcome steps
        run: echo "CI pipeline for this repo"
      - name: checkout repository
        uses: actions/checkout@v4
      - name: Lint HTML Files
        run: npx htmlhint "**/*.html"   
      - name: lint CSS Files
        run: npx stylelint "**/*.css"

